service: authorization-service

frameworkVersion: '3'

provider:
  name: aws
  stage: dev
  runtime: nodejs14.x
  region: eu-west-1

  environment:
    CREDENTIALS: ${ssm(${self:provider.region}):/fshm/${self:provider.stage}/authorizer/credentials}

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: './webpack.config.js'
    includeModules: true
    packager: 'npm'
    excludeFiles: tests/**/*.spec.js

functions:
  basicAuthorizer:
    handler: src/handler.basicAuthorizer
